export const PLATFORMS = 'PLATFORMS'
export const USER = 'USER'
export const FEATURE = 'FEATURE'
export const TECHNOLOGIES = 'TECHNOLOGIES'
export const DATASETS = 'DATASETS'
export const SHAPES = 'SHAPES'
