export { default as createDocument } from './createDocument'
export { default as updateDocument } from './updateDocument'
export { default as deleteDocument } from './deleteDocument'
export { default as getDocument } from './getDocument'
export { default as getId } from './getId'
export { default as getDocuments } from './getDocuments'
